### ISSUE TITLE
Navbar @mhtb32

### ISSUE THREAD

**Issue by mhtb32** [RTROBOTLAB/RTROBOTLAB.github.io#1]
Navbar problems in small devices. Something has to be done with flexes.

**Comment by 1995parham** [comment]
I think you can do this with the bootstrap, see some of the bootstrap examples in its website 😄

**Comment by mhtb32** [comment]
Thank you so much for helping bro :D The code is already written in bootstrap, But there is a problem with how I used flex components, I will review the code whenever university professors let me go 🗡 🗡

**Comment by 1995parham** [comment]
Are these swords use instead of axes? 😂

**Comment by mhtb32** [comment]
Of course 😆

**Comment by mhtb32** [comment]
Issue fixed using collapse element.
